import { Controller, Get, Post, Param, Inject, UseGuards } from '@nestjs/common';
import type { ILogger } from '@shared/interfaces/logging';
import type { ICacheService } from '@shared/interfaces/infrastructure';
import {
  ILogger as ILoggerToken,
  ICacheService as ICacheServiceToken,
} from '@shared/tokens/injection.tokens';
import { RateLimitGuard } from '@api/common/guards/RateLimitGuard.guard';
import { RateLimit, SkipRateLimiting } from '@api/common/decorators/RateLimit.decorator';

@Controller('health')
export class HealthController {
  constructor(
    @Inject(ILoggerToken) private readonly _logger: ILogger,
    @Inject(ICacheServiceToken) private readonly _cacheService: ICacheService,
  ) {}

  @Get()
  async ping() {
    this._logger.LogInfo('Health check hit');

    // Check cache health
    let cacheStatus = 'unknown';
    try {
      const testKey = 'health:check';
      await this._cacheService.set(testKey, { timestamp: Date.now() }, 10);
      const value = await this._cacheService.get(testKey);
      cacheStatus = value ? 'healthy' : 'unhealthy';
      await this._cacheService.remove(testKey);
    } catch (error) {
      cacheStatus = 'error';
      this._logger.LogWarning('Cache health check failed', { error });
    }

    return {
      ok: true,
      now: new Date().toISOString(),
      cache: cacheStatus,
    };
  }

  /**
   * Test Redis caching endpoint
   * GET /health/cache/test/:key
   */
  @Get('cache/test/:key')
  @UseGuards(RateLimitGuard)
  @SkipRateLimiting()
  async testCache(@Param('key') key: string) {
    const cacheKey = `test:cache:${key}`;
    const testData = {
      key,
      timestamp: Date.now(),
      message: 'This is a test cache entry',
      random: Math.random(),
    };

    // Try to get from cache
    const cached = await this._cacheService.get<typeof testData>(cacheKey);

    if (cached) {
      this._logger.LogInfo('Cache hit', { key: cacheKey });
      return {
        status: 'cache_hit',
        data: cached,
        message: 'Data retrieved from cache',
      };
    }

    // Cache miss - set the data
    await this._cacheService.set(cacheKey, testData, 60); // 60 seconds TTL
    this._logger.LogInfo('Cache miss - data set', { key: cacheKey });

    return {
      status: 'cache_miss',
      data: testData,
      message: 'Data set in cache (will be cached for 60 seconds)',
    };
  }

  /**
   * Test Redis caching with getOrSet (thread-safe)
   * GET /health/cache/getorset/:key
   */
  @Get('cache/getorset/:key')
  @UseGuards(RateLimitGuard)
  @SkipRateLimiting()
  async testCacheGetOrSet(@Param('key') key: string) {
    const cacheKey = `test:getorset:${key}`;
    let callCount = 0;

    // This factory will only be called once even with concurrent requests
    const data = await this._cacheService.getOrSet(
      cacheKey,
      async () => {
        callCount++;
        this._logger.LogInfo('Factory called', { key: cacheKey, callCount });
        // Simulate expensive operation
        await new Promise((resolve) => setTimeout(resolve, 100));
        return {
          key,
          timestamp: Date.now(),
          callCount,
          message: 'This data was generated by the factory',
        };
      },
      60, // 60 seconds TTL
    );

    return {
      status: 'success',
      data,
      message: 'Data retrieved using getOrSet (thread-safe)',
    };
  }

  /**
   * Test rate limiting endpoint (strict limit for testing)
   * GET /health/ratelimit/test
   */
  @Get('ratelimit/test')
  @UseGuards(RateLimitGuard)
  @RateLimit({ limit: 5, windowSeconds: 60 })
  async testRateLimit() {
    return {
      status: 'success',
      message: 'Rate limit test endpoint - max 5 requests per minute',
      timestamp: new Date().toISOString(),
    };
  }

  /**
   * Test rate limiting endpoint (very strict for easy testing)
   * GET /health/ratelimit/strict
   */
  @Get('ratelimit/strict')
  @UseGuards(RateLimitGuard)
  @RateLimit({ limit: 3, windowSeconds: 30 })
  async testRateLimitStrict() {
    return {
      status: 'success',
      message: 'Strict rate limit test - max 3 requests per 30 seconds',
      timestamp: new Date().toISOString(),
    };
  }

  /**
   * Clear cache by prefix
   * POST /health/cache/clear/:prefix
   */
  @Post('cache/clear/:prefix')
  @UseGuards(RateLimitGuard)
  @SkipRateLimiting()
  async clearCache(@Param('prefix') prefix: string) {
    await this._cacheService.clearByPrefix(`test:${prefix}:`);
    this._logger.LogInfo('Cache cleared by prefix', { prefix });
    return {
      status: 'success',
      message: `Cache cleared for prefix: test:${prefix}:`,
    };
  }
}
